```{r}
library(tidyverse)
library(janitor)
library(naniar)
library(shiny)
library(shinydashboard)
```
# Import Data
```{r}
spacemission_fixed <- read_csv("data/space_missions_fixed.csv") %>% 
  clean_names() %>%
  separate(location, into = c("site1", "site2", "site3", "site4", "area", "country"), extra = "drop", fill = "left", sep = ",") %>%
  select(-site1, -site2, -site3, -site4) %>%
  separate(date, into = c("year", "month", "date"), sep = "-")
```

```{r}
names(spacemission_fixed)
```


# Graph Outline

```{r}
spacemission_fixed %>%
  ggplot(aes(x = year, y = mission_status, fill = mission_status))+
  geom_col()+
  coord_flip()
```

```{r}
spacemission_test <- spacemission_fixed %>%
  mutate()
```


# App
```{r}
ui <- dashboardPage(
  dashboardHeader(title = "Rocket Statistics from 1957-2018"),
  dashboardSidebar(disable = T),
  dashboardBody(
    fluidRow(
      box(title = "Plot (RENAME PENDING)", width = 12,
          radioButtons("x", "Select Fill", choices = c("mission_status", "rocket_status", "country"),
                       selected = "mission_status"),
          plotOutput("plot")
      ),#closes first box
      box(title = "Rocket Pictures", width = 5,
          selectInput("image_select", "Select Image:", choices=c("cosmos-2i", "cosmos-3m","molniya-m","soyuz-u", "Voshkod")),
          imageOutput("image"),
          selectInput("x", "Select X",)
      ),#closes second box
    )#closes fluid row
  )#closes dashboard body
  
) #closes dashboard page

server <- function(input, output, session) {
  output$image <- renderImage({
    list(src = paste0("images/", input$image_select, ".png"), contentType = "image/png", width = "300px")
  }) #closes render image
  output$plot <- renderPlot({
    spacemission_fixed %>%
      group_by(year) %>%
      ggplot(aes_string(x="year", fill = input$x))+
      geom_bar() + 
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
  }) #closes render plot
    output$plot <- renderPlot({
    spacemission_fixed %>%
      select(rocket, year) %>%
      group_by(year) %>%
      filter(rocket = contains(input$image_select)) %>%
      count(rocket) %>%
      ggplot(aes_string(x = "year", y = "n"))+
      geom_col()
  }) #closes render plot

  session$onSessionEnded(stopApp)
} #closes session

shinyApp(ui, server)
```

  output$plot <- renderPlot({
    spacemission_fixed %>%
      select(rocket, year) %>%
      group_by(year) %>%
      filter(rocket = contains(input$image_select)) %>%
      count(rocket) %>%
      ggplot(aes_string(x = "year", y = "n"))+
      geom_col()
  }) #closes render plot

```{r}
library(shiny)

ui <- dashboardPage(
  dashboardHeader(title = "Rocket Statistics"),
  dashboardSidebar(disable = T),
  dashboardBody(
    fluidRow(
      box(title = "Plot Options", width = 3,
          selectInput("x", "Select Input", choices = c("mission_status", "rocket_status", "country"),
                      selected = "mission_status"),
          ),#closes first box
      box(title = "Rocket Statistics from 1957-2022", width =8,
          plotOutput("plot", width = "600px", height = "500px")
          )#closes the second box
    )#closes fluid row
  )#closes dashboard body
  
) #closes dashboard page

server <- function(input, output, session) {
  output$plot <- renderPlot({
    spacemission_fixed %>%
      group_by(year) %>%
      ggplot(aes_string(x="year", fill = input$x))+
      geom_bar()+
      coord_flip()+
      labs(x = "Count",
           y = "Year")
  }) #closes render plot
  session$onSessionEnded(stopApp)
} #closes session

shinyApp(ui, server)
```

```{r}
spacemission_fixed %>%
  select(rocket) %>%
  group_by(rocket) %>%
  count(rocket) %>%
  arrange(desc(n))
```

