---
title: "Space Mission Presentation"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
library(tidyverse)
library(janitor)
library(naniar)
```

## What Data, and Where is it from?

Sourced from [Maven Analytics](https://mavenanalytics.io/data-playground?page=5&pageSize=5)

```{r include=FALSE}
spacemission <- read_csv("data/space_missions.csv") %>% clean_names()
```

```{r}
glimpse(spacemission)
```
```{r}
miss_var_summary(spacemission)
```


```{r}
spacemission <- spacemission %>%
  separate(date, into = c("year", "month", "date"), sep = "-")
```

```{r}
spacemission %>%
  group_by(year) %>%
  ggplot(aes(x = year)) +
  geom_bar() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r separates location into different parts}
site_spacemission <- spacemission %>%
  separate(location, into = c("road", "site", "state", "country"), extra = "drop", fill = "left", sep = ",")
```

## Check

```{r}
site_spacemission %>%
  group_by(country) %>%
  summarise(total = n()) %>%
  ggplot(aes(x = country, y = total, fill = country)) +
  geom_col() + 
  coord_flip() +
  geom_text(aes(label = total), hjust = -0.2, size = 2, color = "black") + # the first blank column is Brazil
  theme_classic() + 
  theme(legend.position = "bottom", legend.text = element_text(size = 5.5))
```

## Average Price of Mission
```{r}
spacemission %>%
  summarize(mean_cost = mean(price, na.rm = T))
```
## Proportion of Failures to Successes
```{r}
spacemission %>%
  
```


